### ISSUE TITLE
Adjustment of image size in responsive

### ISSUE THREAD

**Issue by Mirsagatov** [zebiniso78/home#8]
![image](https://user-images.githubusercontent.com/62383145/123226923-86de8600-d4ed-11eb-939f-73bfac4fb3f2.png)
![image](https://user-images.githubusercontent.com/62383145/123227052-a2e22780-d4ed-11eb-881d-9284d2b49c86.png)
During the Responsive, the arrows were smaller than in the pictures. Therefore, it would be better to either zoom in on the image or zoom in on the bullet.

**Comment by zebiniso78** [comment]
Thank you for comment, I have corrected it
